version: "3.6"

services:
  zamyatina-postgres:
    image: postgres:15.2-bullseye
    shm_size: 1g
    container_name: zamyatina-postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    networks:
      - zamyatina-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_WALDIR=/var/log/pg_logs
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  zamyatina-app:
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    container_name: zamyatina-app
    networks:
      - zamyatina-network
    depends_on:
      - zamyatina-postgres
    environment:
      - C_FORCE_ROOT='true'
      - PYTHONUNBUFFERED=1
      - LOCAL_PYTEST=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DEBUG=${DEBUG}
      - ENVIRONMENT_TYPE=docker

# TODO: том проверить
networks:
  zamyatina-network:
    driver: bridge

volumes:
  postgres_data: