# Generated by Django 4.2.9 on 2024-02-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TgBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_id", models.BigIntegerField(verbose_name="tg_id")),
                (
                    "name",
                    models.CharField(max_length=225, verbose_name="Имя пользователя"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=225, null=True, verbose_name="Username пользователя"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=18, null=True, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "get_bonus",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Получил бонус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
                "ordering": ["name"],
            },
        ),
    ]
